### ISSUE TITLE
"is" and "contains" is misleading for ranked attributes

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#269]
"is" and "contains" is misleading operator names for ranked attributes such as "sense" in Språkbanken's setup. 

"sense is katt..1" is translated to CQP: `[sense = "\|häst\.\.1:.*"]`
and "sense contains katt..1" to CQP: `[sense contains "häst\.\.1:.*"]`

A better set of operators would be in English/Swedish:
- is possible/är möjlig (contains)
- is not possible/är inte möjlig (does not contain)
- most likely/mest trolig (is)
- not most likely/inte mest trolig (is not)

**Comment by majsan** [comment]
Updates have been done in the code, for the next release, update in corpus config:

```
opts:
    is_possible: rank_contains
    is_not_possible: not_rank_contains
    most_likely: highest_rank
    not_most_likely: not_highest_rank
```
