### ISSUE TITLE
Improve datasetSelect component

### ISSUE THREAD

**Issue by majsan** [spraakbanken/korp-frontend#271]
Currently a component using `datasetSelect` can look like this, for the maximal use case:

```
label: part-of-speech
dataset:
  KN: KN
  MID|MAD|PAD: DL
  NN: NN
escape: false
extended_component: datasetSelect
translation:
  DL: punctuation
  KN: conjunction
 NN: noun
```

`dataset` can either be an object, like in the example, or a list of values. If it is an object, the object keys are the values that will be used in queries and the object values are translation labels for presentation. The translations in `translation` will be used.

This can be improved by moving `attribute.dataset` into the component options, like this:

```
label: part-of-speech
escape: false
extended_component:
  name: datasetSelect
  options:
    dataset:
      KN: KN
      MID|MAD|PAD: DL
      NN: NN
      ...
translation:
  DL: punctuation
  KN: conjunction
  NN: noun
  ...
```

Also, if the translation keys are the same as the dataset, `dataset` could be omitted:

```
label: part-of-speech
escape: false
extended_component: datasetSelect
translation:
  DL: punctuation
  KN: conjunction
  NN: noun
  ...
```
In this example, `DL`, `KN` and `NN` should be automatically included in the dataset.

Also investigate if `escape` could be moved into the component options.
