### ISSUE TITLE
DateInterval not working

### ISSUE THREAD

**Issue by starkadur** [spraakbanken/korp-frontend#292]
I have added -date_interval as a structural attribute for one of my corpora:

  \- date_interval:
      label:
        eng: Time interval
        is: Tímabil
      hide_sidebar: 'true'
      hide_compare: 'true'
      hide_statistics: 'true'
      opts: false
      extended_component: dateInterval

When I search for the word "kona" and the time interval from 2018-01-01 to 2019-01-01 I get no results. When I look at the active cqp-query in advanced search it is like this:

  `[lemma = "kona" & _.date_interval = "20180101,20230104,000000,235959"]`

If I do similar search on the Swedish Korp the active cqp-query looks like this:

`[word = "och" & ((int(_.text_datefrom) = 20180101 & int(_.text_timefrom) >= 094500) | (int(_.text_datefrom) > 20180101 & int(_.text_datefrom) <= 20191231)) & (int(_.text_dateto) < 20191231 | (int(_.text_dateto) = 20191231 & int(_.text_timeto) <= 235959))]`

... and if I change the word from "och" to "kona" and insert this into "Fullständig CQP-fråga" in my version of Korp it works and I get some results.

So how come I don't get the same extended cqp-query when using the datepicker that dateInterval creates, and why does the query I get not work?

**Comment by starkadur** [comment]
I began by adding 

```
common_struct_types:
  date_interval:
    label: 
      eng: time interval
      isl: tímabil
    hide_sidebar: 'true'
    hide_compare: 'true'
    hide_statistics: 'true'
    opts: false
    extended_component: dateInterval
```
to config.yml but that did not make the customized selector appear for the corpora. So I had to add 

```
date_interval:
      label:
        eng: Time interval
        isl: Tímabil
      hide_sidebar: 'true'
      hide_compare: 'true'
      hide_statistics: 'true'
      opts: false
      extended_component: dateInterval
```
into each and every corpora-file. Already there I feel that something is not working correctly. Shouldn't it be enough to add this to config.yml?

I have downloaded all the newest updates from gitHub but the same problems persists.

When looking at cpq.js is notice that the type is _.date_interval and not date_interval so the function  parseDateInterval is not fired. And the value of out in stringifyCqp is:

`_.date_interval` = `"19450101,20221231,000000,235959"`

and thus in the URL it says **_.date_interval** = ... but in Spraakbankens Korp it will be **date_interval==** 

Might this explain the problem to some extent?
